defaults:
  - scope:
      path: ""
    values:
      layout: default
      title: "Every Two Years"
      socialImage: "/media/social/2.png"
      socialDescription: "Want a voice? Join us."
      socialTitle: "Take Back Democracy"
      excerpt_separator: "<!--more-->"
