defaults:
  - scope:
      path: ""
    values:
      title: "Every Two Years"
      socialImage: "https://everytwoyears.org/media/social/2.png"
      socialDescription: "Want a voice? Join us."
      socialTitle: "Take Back Democracy"
